import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Rehenrose App",
  description: "Generated by Rehenrose",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen flex flex-col`}
      >
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
