import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "../providers/AuthProvider";

export const metadata: Metadata = {
  title: "Rehenrose App",
  description: "Generated by Rehenrose",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <main className="flex-grow">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
